Verificar archivos y validar sus datos que sean correctos

In [3]:
import os
import numpy as np

# 📌 Ruta donde están los archivos
OUTPUT_PATH = r"C:\DAVID\CS\2025 0\machine_learning\P3_ML_GP6\reduced_data"

# 📂 Archivos a validar
files_to_check = [
    #"pca_reduced_validation.npy",
    #"pca_reduced_test.npy",
    "lda_reduced_validation.npy",
    "lda_reduced_test.npy"
]

# 🔍 Validar cada archivo
for file in files_to_check:
    file_path = os.path.join(OUTPUT_PATH, file)

    if os.path.exists(file_path):
        data = np.load(file_path)

        print(f"\n📂 Archivo: {file}")
        print(f"   🔹 Forma: {data.shape}")  # Ver tamaño
        print(f"   🔹 Primeras filas:\n{data[:5]}")  # Mostrar primeras 5 filas
        print(f"   🔹 Valores nulos: {np.isnan(data).sum()}")  # Ver si hay NaN
        print("-" * 50)
    else:
        print(f"❌ No se encontró el archivo: {file}")



📂 Archivo: lda_reduced_validation.npy
   🔹 Forma: (193, 6)
   🔹 Primeras filas:
[[-1.71714115 -0.49498607  0.09135714 -0.36684638  0.79289238 -1.84496232]
 [ 1.33808993 -0.27224344  0.36734535 -0.2444233   0.23973242  0.32237309]
 [-3.25441761  2.70149174  0.44237266  0.64631173  0.07372722  0.33385569]
 [ 1.39321368  0.36417838 -0.26394729  0.26827828 -1.53957514  0.02095351]
 [ 1.76900108  1.13897312 -0.08403179  0.29878258  0.35732695  0.49018863]]
   🔹 Valores nulos: 0
--------------------------------------------------

📂 Archivo: lda_reduced_test.npy
   🔹 Forma: (1512, 6)
   🔹 Primeras filas:
[[ 0.1835516   0.1381562   0.87652573 -1.3490736  -0.40571818  0.00780483]
 [-0.02009132  0.1732472  -0.56188205  1.19050985  0.26349447  0.98506649]
 [-1.98691466  1.35134091  1.66311008 -0.37453209  0.17210101 -0.62868951]
 [ 0.6434077  -0.63604493 -0.99888042 -1.82780749 -1.692538    0.07065516]
 [ 0.31873639  1.00522301  0.1609939  -0.12011828  0.57149171  1.94651326]]
   🔹 Valores nulos